image: node:6

before_script:
  - npm install
stages:
  - test
  - deploy
npm_test:
  stage: test
  script:
    - npm build
    - npm test
release:
  stage: deploy
  script:
    - export NPM_TOKEN="097cdf5c-9d2b-4c55-99ba-5af0c5582d08"
    - echo Running release
    - npm run ci-publish || true



