image: node:6

before_script:
  - npm install

stages:
  - test
  - production

test:
  stage: test
  script:
    - npm run build
    - npm test

production:
  stage: production
  script:
    - npm publish
