image: node:6

before_script:
  - npm install
stages:
  - test
  - deploy
npm_test:
  stage: test
  script:
    - npm run build
    - npm test
release:
  stage: deploy
  script:
    - export NPM_TOKEN="16692e96-1c65-4b79-be86-2aa72683dbe1"
    - echo running build
    - npm run build
    - echo running release
    - npm run ci-publish || true



