language: node_js
matrix:
  include:
    - node_js: "lts/*"
    - node_js: 11
    - node_js: 9
    - node_js: 8
  allow_failures:
    - node_js: 11
    - node_js: 9
    - node_js: 8
install:
  - npm install
  - npm install --only=dev
script:
  - npm run coverage:ci
  - npm run coverage:upload
cache:
  directories:
    - "node_modules"
    - "pki"
branches:
  only:
  - master
  - develop
  - LTS
